Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;

namespace ColFinanzas.Controllers
{
    public class EmpresaController : Controller
    {
        public IActionResult InicioEmpresa()
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ColFinanzas.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/TrabajadorController.cs
using Microsoft.AspNetCore.Mvc;

namespace ColFinanzas.Controllers
{
    public class TrabajadorController : Controller
    {
        public IActionResult InicioTrabajador()
        {
            return View();
        }

        public IActionResult Independiente()
        {
            return View();
        }

        public IActionResult Empleado()
        {
            return View();
        }
    }
}

Views/Empresa/InicioEmpresa.cshtml
<h1>Hola mundo inicio empresa!</h1>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container text-center">
      
    <div class="alert alert-success" role="alert">
    <!--<h4 class="alert-heading">¡Cálcule fácil!</h4>-->
    <p>¿Cuánto descontar por retención en la fuente?</p>
    <p>¿Cuánto pagar por prestación de servicios?</p>
    <p class="mb-0">¿Cuánto me cuesta realmente un empleado?</p>
    </div>

    <a class="btn btn-primary btn-lg btn-block" asp-controller="Empresa" asp-action="InicioEmpresa">
        Soy Empresa
    </a>
    <a class="btn btn-success btn-lg btn-block" asp-controller="Trabajador" asp-action="InicioTrabajador">Soy Trabajador</a>
    </a>      

</div><!-- /.container -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ColFinanzas</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" asp-controller="Home" asp-action="Index">Cuentas Colombia</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
          </li>
          <!--<li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <!--<form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Cuentas Claras Colombia </p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
         <script src="~/lib/tether/dist/js/tether.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Trabajador/Empleado.cshtml
<h1>Empleado!</h1>
<br>

<div class="input-group input-group-lg">
  <span class="input-group-addon" id="sizing-addon1">$</span>
  <input type="text" class="form-control" placeholder="Salario Mensual" aria-describedby="sizing-addon1">
</div>

Views/Trabajador/Independiente.cshtml
<h1>Independiente!</h1>

Views/Trabajador/InicioTrabajador.cshtml
@{
    ViewData["Title"] = "Inicio Trabajador";
}
<div class="container">
     <a class="btn btn-primary btn-lg btn-block" asp-controller="Trabajador" asp-action="Independiente">
            Soy Independiente
        </a>
        <a class="btn btn-success btn-lg btn-block" asp-controller="Trabajador" asp-action="Empleado">Soy Empleado</a>
</div>